# -*- coding: utf-8 -*-
"""Nội dung CV 3 ngôn ngữ. Chỉ dùng thông tin Phan Cự đã cung cấp — không thêm gì khác."""

CONTACT = {
    "email": "Phancu.edu@gmail.com",
    "phone": "0888523894",
    "site": "phandinh.site",
    "linkedin": "",      # bổ sung sau
}

DATA = {
    "vi": {
        "lang_tag": "TIẾNG VIỆT",
        "name": "PHAN ĐÌNH CỰ",
        "role": "Production Management · Manufacturing Operations · Digital Transformation",
        "objective": "Mục tiêu: Giám sát Sản xuất · Phó Quản lý Sản xuất · Quản lý Sản xuất · Quản lý Vận hành (hoặc vị trí tương đương)",
        "tagline": "Kết nối Con người, Quy trình và Công nghệ.",
        "summary": "Trợ lý Giám đốc Nhà máy từ 04/2024, nhà máy ~250 người, 3 xưởng, sản lượng ~1.500 tủ thông minh/tháng. Hằng ngày tôi theo dõi kế hoạch, "
                   "đơn hàng và tiến độ giữa các xưởng, làm báo cáo cho Ban Giám đốc người Trung Quốc. "
                   "Khác biệt của tôi: chuẩn hoá lại cách làm, rồi tự viết công cụ để số liệu rõ ràng và quyết định nhanh hơn.",
        "facts": [("~1.500", "tủ thông minh / tháng"), ("~10", "đơn hàng / tháng"), ("~250", "nhân sự · 3 xưởng"), ("1.100+", "mã kho BTP tự thiết kế")],
        "h_contact": "LIÊN HỆ",
        "h_lang": "NGÔN NGỮ",
        "h_edu": "HỌC VẤN",
        "h_cap": "NĂNG LỰC QUẢN LÝ",
        "h_summary": "TÓM TẮT",
        "h_impact": "TÔI ĐÃ THAY ĐỔI ĐIỀU GÌ",
        "h_exp": "KINH NGHIỆM",
        "h_work": "CÔNG CỤ QUẢN LÝ — TỰ THỰC HIỆN TOÀN BỘ",
        "h_think": "CÁCH LÀM VIỆC",
        "h_dir": "MỤC TIÊU NGHỀ NGHIỆP",
        "langs": [("Tiếng Việt", "Bản ngữ"), ("Tiếng Trung — HSK 4+", "Họp, tài liệu và chuyển tải yêu cầu công việc"), ("English", "Công việc / kỹ thuật")],
        "edu": ["Đại học Sư phạm Kỹ thuật TP. Hồ Chí Minh", "Kỹ thuật Điện tử Công nghiệp"],
        "caps": [
            ("Quản lý sản xuất", "Kế hoạch sản xuất · Quản lý đơn hàng · Theo dõi tiến độ · Phối hợp cán bộ 3 xưởng · Đào tạo cán bộ & công nhân · Báo cáo Ban Giám đốc"),
            ("Quy trình & cải tiến", "ISO 9001 · 5S · Kaizen · Chuẩn hoá quy trình · Biểu mẫu / SOP · Kiểm soát tồn kho"),
            ("Dữ liệu & báo cáo", "Excel · Pandas · SQL / SQLite · Báo cáo sản xuất · Đối chiếu chấm công"),
            ("Công nghệ hỗ trợ", "MES · Quản lý kho · Windows Server · LAN / IP · Triển khai ứng dụng nội bộ"),
            ("AI trong công việc", "Phân tích dữ liệu · Soạn SOP / tài liệu · Hỗ trợ xây công cụ · Tự động hoá"),
        ],
        "impact": [
            ("Kế hoạch sản xuất",
             "Mỗi xưởng giữ một bản kế hoạch riêng",
             "Một hệ thống chung, mọi bộ phận xem cùng một số liệu"),
            ("Theo dõi tiến độ",
             "Muốn biết đơn hàng ở đâu phải đi hỏi từng xưởng",
             "Nhìn màn hình biết đơn đang ở khâu nào: Kim loại → Sơn → Lắp ráp → Xuất hàng"),
            ("Kho bán thành phẩm",
             "Trong hơn 5.000 mã vật tư, kho BTP không tra nhanh được tồn và vị trí",
             "Tự thiết kế hệ thống kho BTP hơn 1.100 mã: tồn, vị trí, lịch sử thao tác"),
            ("Tài liệu nội bộ",
             "Tài liệu nằm rải rác, khó tìm, khó kiểm soát",
             "Một nơi lưu duy nhất, tìm theo phòng ban và thời gian, ai xem được gì rõ ràng"),
            ("Vận hành IT",
             "Lỗi lặp lại, mỗi lần xử lý một kiểu",
             "Cùng một lỗi xử lý cùng một cách, người mới cũng làm được"),
        ],
        "exp": {
            "company": "WEBOX VIỆT NAM",
            "role": "Trợ lý Giám đốc Nhà máy — phụ trách Quản lý Sản xuất",
            "meta": "04/2024 – nay · Nhà máy ~250 nhân sự · 3 xưởng: Kim loại · Sơn · Lắp ráp · môi trường Việt – Trung",
            "groups": [
                ("Quản lý & điều phối", "Theo dõi ~10 đơn hàng/tháng, tương đương ~1.500 tủ thông minh, cùng các đơn gia công linh kiện cao cấp; điều phối qua cán bộ quản lý của 3 xưởng (không trực tiếp quản lý công nhân) và báo cáo Ban Giám đốc người Trung Quốc."),
                ("Quy trình & dữ liệu", "Chuẩn hoá biểu mẫu và cách ghi số liệu; gom kế hoạch, tiến độ và tồn kho về một nguồn duy nhất, có phân quyền và nhật ký thao tác."),
                ("Đào tạo đội ngũ", "Đào tạo công nhân mới vào việc và huấn luyện phương pháp quản lý cho cán bộ cấp trung của các xưởng."),
                ("Công nghệ hỗ trợ", "Là người duy nhất xây dựng và vận hành các hệ thống nội bộ phục vụ quản lý; lo máy tính, mạng và server của nhà máy."),
            ],
        },
        "works": [
            ("WEBOX MES", "Hệ thống quản lý sản xuất nội bộ",
             "Ban Giám đốc xem kế hoạch và tiến độ cả 3 xưởng trên một màn hình. Tôi tự làm toàn bộ: khảo sát, thiết kế, lập trình, triển khai, vận hành.",
             "Node.js · SQLite · Windows Server / LAN"),
            ("Warehouse Management", "Quản lý vật tư và tồn kho",
             "Tôi thiết kế hệ thống kho bán thành phẩm hơn 1.100 mã: biết còn gì, ở đâu, ai vừa thao tác trước khi mua thêm hay điều chuyển.",
             "Node.js · SQLite"),
            ("Document Management", "Quản lý văn bản nội bộ",
             "Tài liệu về một chỗ, tìm nhanh và kiểm soát được ai xem được gì.",
             "Node.js · SQLite · Windows Server"),
            ("Attendance & Data System", "Xử lý dữ liệu chấm công và sản xuất",
             "Đối chiếu và tổng hợp không còn phụ thuộc một người làm tay.",
             "Python · Flask · Pandas · Windows Service"),
        ],
        "think": [("Understand", "Hiểu việc thật"), ("Standardize", "Chuẩn hoá"), ("Make Data Visible", "Đưa dữ liệu ra chỗ thấy được"),
                  ("Use Technology / AI", "Dùng công nghệ & AI"), ("Improve", "Cải thiện dần")],
        "dir": "Giám sát Sản xuất · Phó Quản lý Sản xuất · Quản lý Sản xuất · Quản lý Vận hành (hoặc vị trí tương đương)",
        "dir_note": "Tôi phát triển theo hướng quản lý sản xuất và vận hành. IT và dữ liệu là công cụ giúp tôi quản lý chặt hơn. Sẵn sàng làm việc tại bất kỳ khu vực nào.",
        "labels": {"before": "Trước", "after": "Sau", "value": "Giá trị", "tech": "Công nghệ"},
    },

    "zh": {
        "lang_tag": "中文",
        "name": "潘廷巨",
        "role": "生产管理 · 制造运营 · 数字化转型",
        "objective": "求职目标：生产主管 · 生产副经理 · 生产经理 · 制造 / 运营同等职位",
        "tagline": "连接人员、流程与技术。",
        "summary": "自 2024 年 4 月起在约 250 人、三个车间的制造工厂担任厂长助理。日常协调各车间的计划、订单与进度，"
                   "编制报表并直接对接中方管理层。我的不同之处：先把流程标准化，再自行开发工具，"
                   "让生产数据透明、决策更快 —— 技术是管理手段，而非职业方向。",
        "facts": [("~1,500", "台智能柜 / 月"), ("~10", "张订单 / 月"), ("~250", "人 · 三个车间"), ("1,100+", "半成品仓库编号（自主设计）")],
        "h_contact": "联系方式",
        "h_lang": "语言",
        "h_edu": "教育背景",
        "h_cap": "管理能力",
        "h_summary": "简介",
        "h_impact": "我改变了什么",
        "h_exp": "工作经历",
        "h_work": "自建管理工具（独立完成）",
        "h_think": "工作方式",
        "h_dir": "职业目标",
        "langs": [("越南语", "母语"), ("中文 — HSK 4+", "会议、文件与工作要求双向传达"), ("English", "工作 / 技术沟通")],
        "edu": ["胡志明市师范技术大学", "工业电子技术"],
        "caps": [
            ("生产管理", "生产计划 · 订单管理 · 进度跟踪 · 车间干部协调 · 干部与员工培训 · 向管理层汇报"),
            ("流程与改善", "ISO 9001 · 5S · 改善 · 流程标准化 · 表单 / SOP · 库存管控"),
            ("数据与报表", "Excel · Pandas · SQL / SQLite · 生产报表 · 考勤核对"),
            ("技术支撑", "MES · 仓库管理 · Windows Server · LAN / IP · 内部应用部署"),
            ("AI 应用", "数据分析 · SOP / 文件编写 · 工具开发辅助 · 工作自动化"),
        ],
        "impact": [
            ("生产计划", "计划分散在多个文件，各车间各持一版", "集中到一套系统，各部门读同一组数字"),
            ("进度跟踪", "想知道订单在哪个车间只能逐个去问", "按钣金 → 喷涂 → 装配 → 出货在屏幕上直接跟踪"),
            ("半成品仓库", "全厂 5,000 多个编号中，半成品库存与库位查不快", "自主设计半成品仓库系统，覆盖 1,100 多个编号：库存、库位、操作记录"),
            ("内部文档", "文件分散，检索困难，权限难管控", "统一存放，按部门与时间检索，权限清晰"),
            ("IT 运维", "重复的 IT 操作靠手工，做法不统一", "标准化工具箱 — 同类故障同一处理方式，新人可直接接手"),
        ],
        "exp": {
            "company": "WEBOX 越南有限公司",
            "role": "厂长助理 — 主管生产管理",
            "meta": "2024年4月 – 至今 · 约 250 人工厂 · 三个车间：钣金 · 喷涂 · 装配 · 中越协作环境",
            "groups": [
                ("管理与协调", "跟踪每月约 10 张订单、约 1,500 台智能柜及高端零部件代工订单；通过三个车间的干部协调进度（不直接管理一线工人），并向中方管理层汇报。"),
                ("流程与数据", "规范表单、制度与数据记录方式；把计划、进度与库存收敛到唯一数据源，并配套权限与操作日志。"),
                ("团队培训", "为新入职工人做上岗培训，并向各车间中层干部讲授管理方法。"),
                ("技术支撑", "作为唯一开发者建设并运维服务于管理的内部系统，并负责工厂电脑、网络与服务器。"),
            ],
        },
        "works": [
            ("WEBOX MES", "内部生产管理系统", "管理层在同一界面看到三个车间的计划与进度，无需手工汇总。", "Node.js · SQLite · Windows Server / LAN"),
            ("Warehouse Management", "物料与库存管理", "由我设计的半成品仓库系统覆盖 1,100 多个编号：采购或调拨前先知道有什么、在哪里、谁刚操作过。", "Node.js · SQLite"),
            ("Document Management", "内部文档管理", "文件只有一个存放处，检索快，且能管住谁能看什么。", "Node.js · SQLite · Windows Server"),
            ("Attendance & Data System", "考勤与生产数据处理", "核对与汇总不再依赖某一个人的手工操作。", "Python · Flask · Pandas · Windows Service"),
        ],
        "think": [("Understand", "理解实情"), ("Standardize", "标准化"), ("Make Data Visible", "让数据可见"),
                  ("Use Technology / AI", "运用技术与 AI"), ("Improve", "持续改进")],
        "dir": "生产主管 · 生产副经理 · 生产经理 · 制造 / 运营同等职位",
        "dir_note": "我的发展方向是生产与运营管理。IT、数据与 AI 是让我管得更细、决策更快的工具，而不是职业方向。工作地点不限。",
        "labels": {"before": "此前", "after": "此后", "value": "价值", "tech": "技术"},
    },

    "en": {
        "lang_tag": "ENGLISH",
        "name": "PHAN DINH CU",
        "role": "Production Management · Manufacturing Operations · Digital Transformation",
        "objective": "Target roles: Production Supervisor · Deputy Production Manager · Production Manager · Operations Manager (or equivalent)",
        "tagline": "Connecting People, Process and Technology.",
        "summary": "Assistant to the factory manager since April 2024, in a plant of around 250 people across three workshops. I coordinate plans, "
                   "orders and progress through workshop supervisors and report directly to Chinese-speaking management. "
                   "What sets me apart: I standardise the process first, then build the tools that make production data transparent — "
                   "technology is a management instrument, not my career track.",
        "facts": [("~1,500", "smart lockers / month"), ("~10", "orders / month"), ("~250", "people · 3 workshops"), ("1,100+", "codes in warehouse I designed")],
        "h_contact": "CONTACT",
        "h_lang": "LANGUAGES",
        "h_edu": "EDUCATION",
        "h_cap": "MANAGEMENT CAPABILITIES",
        "h_summary": "SUMMARY",
        "h_impact": "WHAT I CHANGED",
        "h_exp": "EXPERIENCE",
        "h_work": "MANAGEMENT TOOLS — BUILT SINGLE-HANDEDLY",
        "h_think": "HOW I WORK",
        "h_dir": "TARGET ROLES",
        "langs": [("Vietnamese", "Native"), ("Chinese — HSK 4+", "Meetings, documents, two-way interpreting"), ("English", "Work / technical")],
        "edu": ["Ho Chi Minh City University of Technology and Education", "Industrial Electronics Engineering"],
        "caps": [
            ("Production management", "Production planning · Order management · Progress tracking · Coordination through supervisors · Training · Board reporting"),
            ("Process & improvement", "ISO 9001 · 5S · Kaizen · Process standardisation · Forms / SOP · Stock control"),
            ("Data & reporting", "Excel · Pandas · SQL / SQLite · Production reporting · Attendance reconciliation"),
            ("Supporting technology", "MES · Warehouse control · Windows Server · LAN / IP · Internal app deployment"),
            ("AI at work", "Data analysis · SOP / documents · Tool development support · Automation"),
        ],
        "impact": [
            ("Production planning", "Plans scattered across files, one version per workshop", "One system — every department reads the same numbers"),
            ("Progress tracking", "Finding an order meant asking each workshop", "Tracked on screen along metal → paint → assembly → shipping"),
            ("Semi-finished stock", "Among 5,000+ material codes, stock and location were slow to find", "Designed the warehouse system for 1,100+ codes: stock, location, history"),
            ("Internal documents", "Scattered, hard to search, access hard to control", "One place, searchable by department and period, clear permissions"),
            ("IT operations", "Repetitive IT tasks by hand, differently each time", "Standardised toolkit — same fault, same fix, anyone can pick it up"),
        ],
        "exp": {
            "company": "WEBOX VIETNAM",
            "role": "Assistant to the Factory Manager — Production Management",
            "meta": "04/2024 – present · Plant of ~250 people · three workshops: metal · paint · assembly · Vietnamese – Chinese environment",
            "groups": [
                ("Management & coordination", "Tracking ~10 orders and ~1,500 smart lockers a month plus OEM component orders; coordinating through the supervisors of three workshops — no direct line management of operators — and reporting to Chinese-speaking management."),
                ("Process & data", "Standardising forms, rules and how data is recorded; consolidating plans, progress and stock into a single source with permissions and audit logs."),
                ("Team training", "Onboarding new operators and coaching workshop supervisors on management method."),
                ("Supporting technology", "Sole builder and operator of the internal systems serving management; running plant computers, network and server."),
            ],
        },
        "works": [
            ("WEBOX MES", "Internal manufacturing management system", "Management sees all three workshops on one screen. Sole builder: analysis, design, development, deployment, operation.", "Node.js · SQLite · Windows Server / LAN"),
            ("Warehouse Management", "Material and stock control", "A warehouse system I designed for 1,100+ semi-finished codes: what is on hand, where it sits and who touched it.", "Node.js · SQLite"),
            ("Document Management", "Internal document control", "One place for documents, quick to search, with control over who sees what.", "Node.js · SQLite · Windows Server"),
            ("Attendance & Data System", "Attendance and production data processing", "Reconciliation and consolidation no longer depend on one person working by hand.", "Python · Flask · Pandas · Windows Service"),
        ],
        "think": [("Understand", "the real work"), ("Standardize", "the process"), ("Make Data Visible", "to everyone"),
                  ("Use Technology / AI", "where it repeats"), ("Improve", "continuously")],
        "dir": "Production Supervisor · Deputy Production Manager · Production Manager · Operations Manager (or equivalent)",
        "dir_note": "My track is production and operations management. IT, data and AI are the tools that let me manage tighter and decide faster. Open to relocation — no location preference.",
        "labels": {"before": "Before", "after": "After", "value": "Value", "tech": "Tech"},
    },
}
